In [1]:
%pip install yfinance

Requirement already satisfied: yfinance in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (2.2.5)
Requirement already satisfied: pandas>=1.3.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: peewee>=3.16.2 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (4.5.2)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (4.25.8)
Requirement already satisfied: pytz>=2022.5 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: requests>=2.31 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: websockets>=13.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from yfinance) (17.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from curl_cffi>=0.15->yfinance) (2025.4.26)
Requirement already satisfied: pycparser in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shifa\anaconda3\envs\data_analysis\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import yfinance as yf
import pandas as pd

print("Python is working!")
print("yfinance version:", yf.__version__)

Python is working!
yfinance version: 1.7.0

In [3]:
import yfinance as yf

apple = yf.Ticker("AAPL")

data = apple.history(
    start="2021-10-01",
    end="2026-09-30"
)

data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-10-01 00:00:00-04:00,138.405160,139.400043,135.683881,139.136688,94639600,0.0,0.0
2021-10-04 00:00:00-04:00,138.268556,138.707484,134.864521,135.713089,98322000,0.0,0.0
2021-10-05 00:00:00-04:00,136.054517,138.736787,135.927714,137.634613,80861100,0.0,0.0
2021-10-06 00:00:00-04:00,136.035028,138.649016,134.962114,138.502716,83221100,0.0,0.0
2021-10-07 00:00:00-04:00,139.536579,140.668013,139.204956,139.760910,61732700,0.0,0.0

In [4]:
data.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

In [5]:
data.shape

(1253, 7)

In [6]:
import yfinance as yf
import pandas as pd

tickers = [
    "SPY",
    "QQQ",
    "AAPL",
    "MSFT",
    "JPM",
    "GLD",
    "TLT",
    "AGG"
]

frames = []

for ticker in tickers:
    print(f"Downloading {ticker}...")
    
    data = yf.Ticker(ticker).history(
        start="2021-10-01",
        end="2026-09-30"
    ).reset_index()
    
    data["ticker"] = ticker
    
    frames.append(data)

raw = pd.concat(frames, ignore_index=True)

raw.head()

Downloading SPY...
Downloading QQQ...
Downloading AAPL...
Downloading MSFT...
Downloading JPM...
Downloading GLD...
Downloading TLT...
Downloading AGG...

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains,ticker
0,2021-10-01 00:00:00-04:00,403.096594,407.819860,399.589211,406.145660,129240100,0.0,0.0,0.0,SPY
1,2021-10-04 00:00:00-04:00,404.985955,405.883838,398.775534,400.908051,128570000,0.0,0.0,0.0,SPY
2,2021-10-05 00:00:00-04:00,402.404549,407.314887,401.609564,405.079529,90682500,0.0,0.0,0.0,SPY
3,2021-10-06 00:00:00-04:00,401.497274,406.968799,399.879219,406.763031,113032200,0.0,0.0,0.0,SPY
4,2021-10-07 00:00:00-04:00,410.027264,413.104388,409.849554,410.279785,72437500,0.0,0.0,0.0,SPY

In [7]:
raw.shape

(10024, 10)

In [8]:
raw["ticker"].value_counts()

ticker
SPY     1253
QQQ     1253
AAPL    1253
MSFT    1253
JPM     1253
GLD     1253
TLT     1253
AGG     1253
Name: count, dtype: int64

In [9]:
raw.head(10)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains,ticker
0,2021-10-01 00:00:00-04:00,403.096594,407.819860,399.589211,406.145660,129240100,0.0,0.0,0.0,SPY
1,2021-10-04 00:00:00-04:00,404.985955,405.883838,398.775534,400.908051,128570000,0.0,0.0,0.0,SPY
2,2021-10-05 00:00:00-04:00,402.404549,407.314887,401.609564,405.079529,90682500,0.0,0.0,0.0,SPY
3,2021-10-06 00:00:00-04:00,401.497274,406.968799,399.879219,406.763031,113032200,0.0,0.0,0.0,SPY
4,2021-10-07 00:00:00-04:00,410.027264,413.104388,409.849554,410.279785,72437500,0.0,0.0,0.0,SPY
5,2021-10-08 00:00:00-04:00,411.046739,411.430216,408.904888,409.531525,74557400,0.0,0.0,0.0,SPY
6,2021-10-11 00:00:00-04:00,408.876787,411.776230,406.501111,406.566589,65233300,0.0,0.0,0.0,SPY
7,2021-10-12 00:00:00-04:00,407.483213,407.885387,404.780176,405.565826,71181200,0.0,0.0,0.0,SPY
8,2021-10-13 00:00:00-04:00,406.585309,407.838611,403.620416,407.024902,72974000,0.0,0.0,0.0,SPY
9,2021-10-14 00:00:00-04:00,410.672561,414.020959,410.204909,413.871307,70236800,0.0,0.0,0.0,SPY

In [10]:
raw.tail(10)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains,ticker
10014,2026-09-16 00:00:00-04:00,95.680769,95.890034,95.451586,95.471512,9608600,0.0,0.0,0.0,AGG
10015,2026-09-17 00:00:00-04:00,95.870099,95.989677,95.780420,95.989677,8034700,0.0,0.0,0.0,AGG
10016,2026-09-18 00:00:00-04:00,95.730599,95.730599,95.591094,95.620987,6148500,0.0,0.0,0.0,AGG
10017,2026-09-21 00:00:00-04:00,95.860135,95.899995,95.770457,95.870102,9197400,0.0,0.0,0.0,AGG
10018,2026-09-22 00:00:00-04:00,95.929884,95.969743,95.750520,95.909958,7162700,0.0,0.0,0.0,AGG
10019,2026-09-23 00:00:00-04:00,95.740561,95.750520,94.913491,95.072929,17281500,0.0,0.0,0.0,AGG
10020,2026-09-24 00:00:00-04:00,95.132715,95.192500,94.594622,94.614548,10688500,0.0,0.0,0.0,AGG
10021,2026-09-25 00:00:00-04:00,94.664372,94.833770,94.405288,94.783951,15486800,0.0,0.0,0.0,AGG
10022,2026-09-28 00:00:00-04:00,94.375398,94.494977,94.146215,94.315613,14248500,0.0,0.0,0.0,AGG
10023,2026-09-29 00:00:00-04:00,94.315612,94.365430,93.996742,94.265785,16726300,0.0,0.0,0.0,AGG

In [11]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10024 entries, 0 to 10023
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           10024 non-null  datetime64[ns, America/New_York]
 1   Open           10024 non-null  float64
 2   High           10024 non-null  float64
 3   Low            10024 non-null  float64
 4   Close          10024 non-null  float64
 5   Volume         10024 non-null  int64
 6   Dividends      10024 non-null  float64
 7   Stock Splits   10024 non-null  float64
 8   Capital Gains  6265 non-null   float64
 9   ticker         10024 non-null  object
dtypes: datetime64[ns, America/New_York](1), float64(7), int64(1), object(1)
memory usage: 783.3+ KB

In [12]:
raw.to_csv(
    "../data/raw/prices_raw.csv",
    index=False
)

print("Raw dataset saved successfully!")

Raw dataset saved successfully!

In [13]:
import pandas as pd

check = pd.read_csv("../data/raw/prices_raw.csv")

print(check.shape)
print(check.head())

(10024, 10)
                        Date        Open        High         Low       Close  \
0  2021-10-01 00:00:00-04:00  403.096594  407.819860  399.589211  406.145660
1  2021-10-04 00:00:00-04:00  404.985955  405.883838  398.775534  400.908051
2  2021-10-05 00:00:00-04:00  402.404549  407.314887  401.609564  405.079529
3  2021-10-06 00:00:00-04:00  401.497274  406.968799  399.879219  406.763031
4  2021-10-07 00:00:00-04:00  410.027264  413.104388  409.849554  410.279785

      Volume  Dividends  Stock Splits  Capital Gains ticker
0  129240100        0.0           0.0            0.0    SPY
1  128570000        0.0           0.0            0.0    SPY
2   90682500        0.0           0.0            0.0    SPY
3  113032200        0.0           0.0            0.0    SPY
4   72437500        0.0           0.0            0.0    SPY

In [14]:
check["ticker"].unique()

array(['SPY', 'QQQ', 'AAPL', 'MSFT', 'JPM', 'GLD', 'TLT', 'AGG'],
      dtype=object)